package com.bjpowernode.crm.settings.domain;

public class DicValue {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dictionary_value.id
     *
     * @mbggenerated Fri Aug 05 16:22:17 CST 2022
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dictionary_value.value
     *
     * @mbggenerated Fri Aug 05 16:22:17 CST 2022
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dictionary_value.text
     *
     * @mbggenerated Fri Aug 05 16:22:17 CST 2022
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dictionary_value.orderNo
     *
     * @mbggenerated Fri Aug 05 16:22:17 CST 2022
     */
    private Long orderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dictionary_value.typeCode
     *
     * @mbggenerated Fri Aug 05 16:22:17 CST 2022
     */
    private String typecode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dictionary_value.id
     *
     * @return the value of tbl_dictionary_value.id
     *
     * @mbggenerated Fri Aug 05 16:22:17 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dictionary_value.id
     *
     * @param id the value for tbl_dictionary_value.id
     *
     * @mbggenerated Fri Aug 05 16:22:17 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dictionary_value.value
     *
     * @return the value of tbl_dictionary_value.value
     *
     * @mbggenerated Fri Aug 05 16:22:17 CST 2022
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dictionary_value.value
     *
     * @param value the value for tbl_dictionary_value.value
     *
     * @mbggenerated Fri Aug 05 16:22:17 CST 2022
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dictionary_value.text
     *
     * @return the value of tbl_dictionary_value.text
     *
     * @mbggenerated Fri Aug 05 16:22:17 CST 2022
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dictionary_value.text
     *
     * @param text the value for tbl_dictionary_value.text
     *
     * @mbggenerated Fri Aug 05 16:22:17 CST 2022
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dictionary_value.orderNo
     *
     * @return the value of tbl_dictionary_value.orderNo
     *
     * @mbggenerated Fri Aug 05 16:22:17 CST 2022
     */
    public Long getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dictionary_value.orderNo
     *
     * @param orderno the value for tbl_dictionary_value.orderNo
     *
     * @mbggenerated Fri Aug 05 16:22:17 CST 2022
     */
    public void setOrderno(Long orderno) {
        this.orderno = orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dictionary_value.typeCode
     *
     * @return the value of tbl_dictionary_value.typeCode
     *
     * @mbggenerated Fri Aug 05 16:22:17 CST 2022
     */
    public String getTypecode() {
        return typecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dictionary_value.typeCode
     *
     * @param typecode the value for tbl_dictionary_value.typeCode
     *
     * @mbggenerated Fri Aug 05 16:22:17 CST 2022
     */
    public void setTypecode(String typecode) {
        this.typecode = typecode == null ? null : typecode.trim();
    }
}