package com.bjpowernode.crm.settings.mapper;

import com.bjpowernode.crm.settings.domain.DicValue;

import java.util.List;

public interface DicValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dictionary_value
     *
     * @mbggenerated Fri Aug 05 16:22:17 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dictionary_value
     *
     * @mbggenerated Fri Aug 05 16:22:17 CST 2022
     */
    int insert(DicValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dictionary_value
     *
     * @mbggenerated Fri Aug 05 16:22:17 CST 2022
     */
    int insertSelective(DicValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dictionary_value
     *
     * @mbggenerated Fri Aug 05 16:22:17 CST 2022
     */
    DicValue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dictionary_value
     *
     * @mbggenerated Fri Aug 05 16:22:17 CST 2022
     */
    int updateByPrimaryKeySelective(DicValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dictionary_value
     *
     * @mbggenerated Fri Aug 05 16:22:17 CST 2022
     */
    int updateByPrimaryKey(DicValue record);

    /**
     * 根绝typeCode查询DicValue
     */
    List<DicValue> selectDicValueByTypeCode(String typeCode);
}